In [1]:
#calcul du cheminement 
import numpy as np 
import pandas as pd 
from utils import *

In [ ]:
## need to import the files 
file = pd.read_excel(r'test23.xlsx' ,nrows = 30)
file

,station,serie,point_visé,cg,rcg,cd,rcd,moyenne,distnacescg,distancecd,distancemoy
0,TOPO1,1.0,TOPO2,0.0000,NaN,200.0036,NaN,NaN,36.8878,36.8708,NaN
1,NaN,NaN,M1,3.5968,NaN,203.5806,NaN,NaN,60.1404,60.1400,NaN
2,NaN,NaN,TOPO2,0.0008,NaN,200.0058,NaN,NaN,36.8800,36.8880,NaN
3,M1,1.0,TOPO1,0.0000,NaN,200.0000,NaN,NaN,60.5478,60.1588,NaN
4,NaN,NaN,M2,317.1028,NaN,117.0828,NaN,NaN,49.0744,49.0710,NaN
5,NaN,NaN,TOPO1,399.9968,NaN,199.9990,NaN,NaN,60.2534,60.1580,NaN
6,M2,1.0,M1,0.0000,NaN,200.0006,NaN,NaN,49.0490,49.0600,NaN
7,NaN,NaN,M3,159.9032,NaN,359.9080,NaN,NaN,58.8596,58.8500,NaN
8,NaN,NaN,M1,0.0010,NaN,200.0002,NaN,NaN,49.0590,49.0600,NaN
9,M3,1.0,M2,0.0000,NaN,200.0002,NaN,NaN,58.8620,58.8500,NaN
10,NaN,NaN,VETO6,331.1206,NaN,131.1274,NaN,NaN,30.5710,30.5700,NaN
11,NaN,NaN,M2,0.0001,NaN,200.0014,NaN,NaN,58.8600,58.8600,NaN
12,VETO6,1.0,M3,0.0000,NaN,200.0022,NaN,NaN,30.5900,30.5800,NaN
13,NaN,NaN,TOPO1,268.6032,NaN,68.6052,NaN,NaN,105.3830,105.3900,NaN
14,NaN,NaN,M3,0.0018,NaN,200.0004,NaN,NaN,30.5800,30.5830,NaN

In [4]:
angles = np.zeros(int(len(file.rcg) / 3 ))
rcgg = np.zeros(len(file.rcg))
rcdd = np.zeros(len(file.rcg))
cd = file.cd
cg = file.cg
moyenne = np.zeros(len(file.rcg)) 
n = len(file.rcg) 
for i in range(1 , n  , 3 ) : 
    p = file.cg[i+1] - file.cg[i-1]
    if p> 399  :
        rcgg[i] = roundd(file.cg[i] - (file.cg[i+1]+400+file.cg[i-1])/2)
    else: 
        rcgg[i] =  roundd(file.cg[i] - (file.cg[i+1] +file.cg[i-1])/2)
for i in range(1 , n  , 3 ) : 
    p = file.cd[i+1] - file.cd[i-1]
    if p> 399  :
        rcdd[i] =  roundd(file.cd[i] - (file.cd[i+1]+400+file.cd[i-1])/2)
    else: 
        rcdd[i] =  roundd(file.cd[i] - (file.cd[i+1] +file.cd[i-1])/2)
    moyenne[i] = ((rcdd[i] + rcgg[i]) / 2 )  
    angles[i//3] = moyenne[i]
file.rcg = rcgg 
file.rcd = rcdd 
file.moyenne = moyenne
file

,station,serie,point_visé,cg,rcg,cd,rcd,moyenne,distnacescg,distancecd,distancemoy
0,TOPO1,1.0,TOPO2,0.0000,0.0000,200.0036,0.0000,0.00000,36.8878,36.8708,NaN
1,NaN,NaN,M1,3.5968,3.5964,203.5806,3.5759,3.58615,60.1404,60.1400,NaN
2,NaN,NaN,TOPO2,0.0008,0.0000,200.0058,0.0000,0.00000,36.8800,36.8880,NaN
3,M1,1.0,TOPO1,0.0000,0.0000,200.0000,0.0000,0.00000,60.5478,60.1588,NaN
4,NaN,NaN,M2,317.1028,317.1044,117.0828,317.0833,317.09385,49.0744,49.0710,NaN
5,NaN,NaN,TOPO1,399.9968,0.0000,199.9990,0.0000,0.00000,60.2534,60.1580,NaN
6,M2,1.0,M1,0.0000,0.0000,200.0006,0.0000,0.00000,49.0490,49.0600,NaN
7,NaN,NaN,M3,159.9032,159.9027,359.9080,159.9076,159.90515,58.8596,58.8500,NaN
8,NaN,NaN,M1,0.0010,0.0000,200.0002,0.0000,0.00000,49.0590,49.0600,NaN
9,M3,1.0,M2,0.0000,0.0000,200.0002,0.0000,0.00000,58.8620,58.8500,NaN
10,NaN,NaN,VETO6,331.1206,331.1206,131.1274,331.1266,331.12360,30.5710,30.5700,NaN
11,NaN,NaN,M2,0.0001,0.0000,200.0014,0.0000,0.00000,58.8600,58.8600,NaN
12,VETO6,1.0,M3,0.0000,0.0000,200.0022,0.0000,0.00000,30.5900,30.5800,NaN
13,NaN,NaN,TOPO1,268.6032,268.6023,68.6052,268.6039,268.60310,105.3830,105.3900,NaN
14,NaN,NaN,M3,0.0018,0.0000,200.0004,0.0000,0.00000,30.5800,30.5830,NaN

In [5]:
n = 1  # nombre de serie par mesure rops
angles_finales = np.zeros(int(len(angles) / n )) # nombre de serie par mesure  
for i in range(0 , len(angles) , n )  : 
    somme = 0 
    for j in range(i , i + n ) : 
        somme  = somme + angles[j]
    
    angles_finales[i//n] = somme / n 
print(angles_finales)

[  3.58615 317.09385 159.90515 331.1236  268.6031 ]

In [6]:
#calcule de la fermeture puis correction 
REF_depart = [364387.872 , 376197.365 ] #364387,872 376197,365 364387,872 376197,365
DEP = [364367.943, 376228.353]   #364367,943 376228,353 364367,943 376228,353
REF_arriv = [364367.943, 376228.353]
ARRIV = [364300.889,376147.112]
try :
    G_arriv = gisement(ARRIV[0] , ARRIV[1],REF_arriv[0],REF_arriv[1])
    #G_depart = gisement(DEP[0] ,DEP[1] , REF_depart[0] , REF_depart[1]  )
    G_depart = gisement( REF_depart[0] , REF_depart[1],DEP[0] ,DEP[1] )
    n = len(angles_finales)
    gisements = np.zeros(n+1) 
    gisements[0] = G_depart 
    for  i in range(1,n+1 )   : 
        gisements[i] = roundd(gisements[i-1] + 200 + angles_finales[i-1] )
except ValueError : 
    print("coordonnee non valide ")
print(G_depart) 
print(gisements)  
print(G_arriv)
f = G_arriv - gisements[-1]
print(f)
#correction des angles 
angles_compensee = np.zeros(n)
for i in range(n) :
    angles_compensee[i] = angles_finales[i] + f / n
print(angles_finales)
print(angles_compensee)

363.6157
[363.6157 167.2019 284.2958 244.2009 375.3245  43.9276]
43.9281
0.0005000000000023874
[  3.58615 317.09385 159.90515 331.1236  268.6031 ]
[  3.58625 317.09395 159.90525 331.1237  268.6032 ]

In [7]:
G_arriv = gisement(ARRIV[0] , ARRIV[1],REF_arriv[0],REF_arriv[1])
G_arriv

43.9281

In [8]:
gisements[-1]

43.9276

In [17]:
#verfication des distances 
distances = [60.1493 , 49.1507 , 58.8586 , 30.579]
d= np.zeros(len(distances ))
#ajouter la correction 
hm = 44.95
rt  = 6400 * 10**(3)
k = 0.36
def distancecorr(d) : 
    return (1 - k / 1000) * (1 - hm/rt) * d
for i in range(len(distances)) : 
    d[i] = distancecorr(distances[i])
d

array([60.12722395, 49.13266067, 58.83699766, 30.56777687])

In [18]:
#faut verifier avec le canevas ploygonal #VERSION OPTIMISE PP 
try :
    #angles_finaless = [264.9386 , 232.2441, 144.9523, 210.1670]
    G_depart = gisement(REF_depart[0] , REF_depart[1], DEP[0] ,DEP[1] )
    #G_depart = gisement(DEP[0] ,DEP[1] , REF_depart[0] , REF_depart[1])
    m  = len(angles_compensee)
    gisements_corr = np.zeros(m+1)
    gisements_corr[0] = G_depart 
    d = [60.12722395, 49.03899506, 58.83639788, 30.57197533] ##>> need to add user s input 
    X = np.zeros(len(angles_compensee))
    Y = np.zeros(len(angles_compensee))
    X[0] = DEP[0]
    Y[0] = DEP[1]
    for  i in range(0 , m)  : 
        if i < m -1 :
            gisements_corr[i+1] = roundd((gisements_corr[i] + 200 + angles_compensee[i]))
            X[i+1] = X[i] + d[i]*sing(gisements_corr[i+1])
            Y[i+1] = Y[i] + d[i]*cosg(gisements_corr[i+1])
        if i == m-1 :
            gisements_corr[i+1] = roundd(gisements_corr[i] + 200 + angles_compensee[i])          
except ValueError : 
    print("coordonnee non valide ")
print(G_depart) 
print(gisements_corr) 
print(X)
print(Y)
veto2 = [364300.889,376147.112]
fx = X[-1] - veto2[0]
fy = Y[-1] - veto2[1] 
print("la fermeture sur x est : fx = {}".format(fx))
print("la fermeture sur x est : fx = {}".format(fy))
print(np.sqrt(fx**2 + fy**2))

363.6157
[363.6157 167.202  284.2959 244.2012 375.3249  43.9281]
[364367.943      364397.56768346 364350.01316736 364312.36634722
 364300.81125844]
[376228.353      376176.03033579 376164.05573624 376118.8402671
 376147.14442932]
la fermeture sur x est : fx = -0.07774155965307727
la fermeture sur x est : fx = 0.03242932178545743
0.08423426267711802

In [37]:
#faut verifier avec le canevas ploygonal #VERSION OPTIMISE PP 
try :
    #angles_finaless = [264.9386 , 232.2441, 144.9523, 210.1670]
    G_depart = gisement(REF_depart[0] , REF_depart[1], DEP[0] ,DEP[1] )
    #G_depart = gisement(DEP[0] ,DEP[1] , REF_depart[0] , REF_depart[1])
    m  = len(angles_compensee)
    gisements_corr = np.zeros(m+1)
    gisements_corr[0] = G_depart 
    d = [36.8796 , 60.1493 , 49.057 , 58.858 , 30,5832] ##>> need to add user s input 
    X = np.zeros(len(angles_compensee))
    Y = np.zeros(len(angles_compensee))
    X[0] = DEP[0]
    Y[0] = DEP[1]
    for  i in range(0 , m)  : 
        if i < m -1 :
            gisements_corr[i+1] = roundd((gisements_corr[i] + 200 + angles_compensee[i]))
            X[i+1] = X[i] + d[i]*sing(gisements_corr[i+1])
            Y[i+1] = Y[i] + d[i]*cosg(gisements_corr[i+1])
        if i == m-1 :
            gisements_corr[i+1] = roundd(gisements_corr[i] + 200 + angles_compensee[i])          
except ValueError : 
    print("coordonnee non valide ")
print(G_depart) 
print(gisements_corr) 
print(X)
print(Y)
veto2 = [364300.889,376147.112]
fx = X[-1] - veto2[0]
fy = Y[-1] - veto2[1] 
print(fx)
print(fy)
print(np.sqrt(fx**2 + fy**2))

363.6157
[363.6157 167.202  284.2959 244.2012 375.3249  43.9281]
[364367.943      364386.11357906 364327.78508248 364296.39566841
 364274.14949661]
[376228.353      376196.26040034 376181.57282814 376143.87277597
 376198.36472036]
-26.73950339196017
51.25272036460228
57.80867051248253

In [ ]:
print(gisement())

In [34]:
#faut verifier avec le canevas ploygonal #VERSION OPTIMISE PP 
g = [363.6157 ,167.2019, 284.2958, 244.2009 ,112.5305,
     43.9276]
try :
    #angles_finaless = [264.9386 , 232.2441, 144.9523, 210.1670]
    G_depart = gisement(REF_depart[0] , REF_depart[1], DEP[0] ,DEP[1] )
    #G_depart = gisement(DEP[0] ,DEP[1] , REF_depart[0] , REF_depart[1])
    m  = len(angles_compensee)
    gisements_corr = np.zeros(m+1)
    gisements_corr[0] = G_depart 
    d = [36.8796 , 60.1493 , 49.057 , 58.858 , 30,5832] ##>> need to add user s input 
    X = np.zeros(len(angles_compensee))
    Y = np.zeros(len(angles_compensee))
    X[0] = DEP[0]
    Y[0] = DEP[1]
    for  i in range(0 , m)  : 
        if i < m -1 :
            gisements_corr[i+1] = roundd((gisements_corr[i] + 200 + angles_compensee[i]))
            X[i+1] = X[i] + d[i]*sing(g[i+1])
            Y[i+1] = Y[i] + d[i]*cosg(g[i+1])
        if i == m-1 :
            gisements_corr[i+1] = roundd(gisements_corr[i] + 200 + angles_compensee[i])          
except ValueError : 
    print("coordonnee non valide ")
print(G_depart) 
print(gisements_corr) 
print(X)
print(Y)
veto2 = [364300.889,376147.112]
fx = X[-1] - veto2[0]
fy = Y[-1] - veto2[1] 
print(fx)
print(fy)
print(np.sqrt(fx**2 + fy**2))

363.6157
[363.6157 167.202  284.2959 244.2012 375.3249  43.9281]
[364367.943      364386.11362947 364327.78515596 364296.39591955
 364354.11747171]
[376228.353      376196.26042888 376181.57276506 376143.87256497
 376132.36228349]
53.22847171284957
-14.7497165093082
55.23426778722232

In [13]:
l = [131.18520 , 310.93800 , 319.03740 , 327.28480 
     ,359.80420, 
     348.14720,327.87860,393.79600,393.49300,390.00840,379.13780,392.04600,380.57200,380.40620
     ,325.48000,350.92400,351.47980,350.23380,353.63880,321.98840,17.37580,51.51060]
print(len(l))
c = l[0]
L= np.zeros(len(l))
for i in range(len(l)) : 
    L[i] = roundd(l[i] - c)
for  i in range(len(l)) : 
    print(L[i])

22
0.0
179.7528
187.8522
196.0996
228.619
216.962
196.6934
262.6108
262.3078
258.8232
247.9526
260.8608
249.3868
249.221
194.2948
219.7388
220.2946
219.0486
222.4536
190.8032
286.1906
320.3254